version: '3'

services:
  reverse-proxy:
    image: traefik
    command: --api --docker 
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry:2
    restart: unless-stopped
    labels:
      - traefik.port=5000
      - traefik.frontend.rule=Host:reg.kubernetes.lol
      - traefik.frontend.auth.basic=alec:registry
    volumes:
      - /var/lib/registry:/var/lib/registry
