defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = https
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "aleccunningham96@gmail.com"
storage = "acme.json"
onDemand = true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entrypoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "tcp://127.0.0.1:2375"
domain = "docker.localhost"
watch = true
